name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx-setup
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: amanmyrat/vocal_instrumental:latest
      - name: Build Docker image for linux/arm64/v8
        id: build-arm-image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: amanmyrat/vocal_instrumental:linux.arm64.v8
          platforms: linux/arm64/v8

      # - name: Upload image artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: docker-image
      #     path: ${{ steps.build-image.outputs.artifact }}

