name: Docker Compose Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub (optional)
        if: github.event_name == 'push' && secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: docker compose -f path/to/your/docker-compose.yml build --cache-from type=local,src=.docker

      - name: Push Docker images
        run: docker compose -f path/to/your/docker-compose.yml push
