name: Docker Compose Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Use a pre-defined action for logging in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: docker-compose -f backend/docker-compose.yml build

      - name: Push Docker images to Docker Hub
        run: docker-compose -f backend/docker-compose.yml push
