# name: Docker Compose Build and Push

# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up environment variables
#         run: |
#           echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
#           echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

#       - name: Login to Docker Hub (optional)
#         if: github.event_name == 'push' && env.DOCKER_USERNAME && env.DOCKER_PASSWORD
#         uses: docker/login-action@v2
#         with:
#           username: ${{ env.DOCKER_USERNAME }}
#           password: ${{ env.DOCKER_PASSWORD }}
 
#       - name: Build and Push Docker images
#         run: docker-compose -f backend/docker-compose.yml build

#         # run: docker-compose -f backend/docker-compose.yml build && docker-compose -f backend/docker-compose.yml push

name: Docker Compose Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker images
        run: docker-compose -f backend/docker-compose.yml build
      # - name: Push Docker images
      #   run: docker-compose -f backend/docker-compose.yml push

